version: "3"
services:
  ai_backend:
    build: ./AI_Backend
    ports:
      - "5001:5000"
    networks:
      - app-network

  ui_backend:
    build: ./Ui_backend
    ports:
      - "5000:5000"
    depends_on:
      - ai_backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
